[package]
name = "lldap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
bytes = "1.6.0"
hex = "0.4.3"
rasn = "0.15.0"
rasn-ldap = "0.15.0"
